Use cookies to perform operations on behalf of the user
googleinterns/step222-2020 pull request #15
Opened 2020-08-28 09:53 UTC by AlexandraImbrisca

- In order to set up the user entities, I associated a separate cookie for sending the id_token to the server.
- I implemented a separate class for getting specific data associated with the user account (e.g. client id, payload).
- The servlets and the DatastoreAccess.java file have been extended to include more functionalities (e.g. getting only the groups joined by the user, joining a new group).

Testing and more error checking will be added afterwards.

2020-08-28 11:06 UTC, csperl requested changes
I did not fully review it yet, but I want to give early feedback about things which apply to most of the code.

Please address them and let me know once you are done :)

2020-08-28 11:06 UTC, csperl commented on src/main/java/com/google/lecturechat/data/DatastoreAccess.java
> +    if (!isRegistered) {
Avoid nesting by finishing early:

if (!isUserRegistered(userId)) {
  return;
}

2020-08-28 11:06 UTC, csperl commented on src/main/java/com/google/lecturechat/data/DatastoreAccess.java
> +      Transaction transaction = datastore.beginTransaction();
I don't think that a transaction is necessary here. Remember in your early classes you simply added entries to the database by calling the put function on the DatastoreService: https://github.com/AlexandraImbrisca/STEP/blob/master/portfolio/src/main/java/com/google/sps/servlets/NewCommentServlet.java#L44

Feel free to read about Transactions and when you need them. https://cloud.google.com/datastore/docs/concepts/transactions

2020-08-28 11:12 UTC, AlexandraImbrisca commented on src/main/java/com/google/lecturechat/data/AuthStatus.java
> +        String idToken = java.net.URLDecoder.decode(encodedIdToken, StandardCharsets.UTF_8.name());
I actually tried without decoding and apparently the function doesn't decode it automatically.

2020-08-28 11:49 UTC, AlexandraImbrisca commented on src/main/java/com/google/lecturechat/data/AuthStatus.java
> +    if (optionalIdToken.isPresent()) {
My bad! The id should also be verified :)

2020-08-28 12:01 UTC, AlexandraImbrisca commented on src/main/java/com/google/lecturechat/data/DatastoreAccess.java
> +      Transaction transaction = datastore.beginTransaction();
I read the documentation again and understood it better. Thank you! :)

2020-08-29 14:01 UTC, csperl requested changes
Please add a TODO somewhere that you also verify that the domain of the user who signes-in is a google.com account.

2020-08-31 06:50 UTC, AlexandraImbrisca commented
About the user domain, we don't actually have to verify it in the code since we already included this restriction in the OAuth 2.0 consent screen. The user is able to use only Google accounts that have the domain google.com. If the domain is not google.com than the sign in is incomplete and the request is not sent to the server. Do you think we should also include it on the server side?

2020-08-31 07:38 UTC, csperl commented
> About the user domain, we don't actually have to verify it in the code since we already included this restriction in the OAuth 2.0 consent screen. The user is able to use only Google accounts that have the domain google.com. If the domain is not google.com than the sign in is incomplete and the request is not sent to the server. Do you think we should also include it on the server side?

I see, sounds good for now.

2020-08-31 07:42 UTC, csperl approved these changes

2020-08-31 07:49 UTC, merged